version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/dr-dobbs/Maven - Building Complex Systems/Code"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"